import { Landmark, BookOpen, Pencil } from "lucide-react";
export const categories = [
  {
    id: 1,
    title: "Company Registration",
    description: "Limited Liability Company",
    icon: Landmark,
    students: 32,
    lessons: 4,
    instructor: "SmeGear",
    image: "/businesses/companyregistrationcourse.webp",

    price: "₦5000",
    rating: 5,
    Views: "4375",
    UpdatedAt: "July 28, 2024",
    Category: "Business",
    overView:
      "This course is designed to help you grasp the fundamental requirements and guidance for registering a business with the Corporate Affairs Commission (CAC). Learn how to do a name search, use the CAC portal, and ensure proper registration procedures.",
    info: [
      "Step-by-step guide",
      "Thorough name search",
      "Navigate CAC portal",
      "Avoid registration errors",
      "Access to mentorship",
      "Access to daily marketing content",
      "Accredited Agent Portal",
      "Community of CAC agents",
    ],
  },
  {
    id: 2,
    title: "NGO Brand Registration",
    description: "Comprehensive Courses",
    icon: BookOpen,
    students: 32,
    lessons: 4,
    instructor: "SmeGear",
    image: "/businesses/ngoregistration.webp",

    price: "₦5000",
    rating: 5,
    Views: "4375",
    UpdatedAt: "July 28, 2024",
    Category: "Business",
    overView:
      "This course is designed to help you grasp the fundamental requirements and guidance for registering a business with the Corporate Affairs Commission (CAC). Learn how to do a name search, use the CAC portal, and ensure proper registration procedures.",
    info: [
      "Step-by-step guide",
      "Thorough name search",
      "Navigate CAC portal",
      "Avoid registration errors",
      "Access to mentorship",
      "Access to daily marketing content",
      "Accredited Agent Portal",
      "Community of CAC agents",
    ],
  },
  {
    id: 3,
    title: "NGO Post Incorporation",
    description: "Comprehensive Courses",
    icon: Pencil,
    students: 32,
    lessons: 4,
    instructor: "SmeGear",
    image: "/businesses/ngopostincorporationmcourse.webp",

    price: "₦5000",
    rating: 5,
    Views: "4375",
    UpdatedAt: "July 28, 2024",
    Category: "Business",
    overView:
      "This course is designed to help you grasp the fundamental requirements and guidance for registering a business with the Corporate Affairs Commission (CAC). Learn how to do a name search, use the CAC portal, and ensure proper registration procedures.",
    info: [
      "Step-by-step guide",
      "Thorough name search",
      "Navigate CAC portal",
      "Avoid registration errors",
      "Access to mentorship",
      "Access to daily marketing content",
      "Accredited Agent Portal",
      "Community of CAC agents",
    ],
  },
  {
    id: 4,
    title: "All Our Cac Courses",
    description: "Comprehensive Courses",
    icon: Pencil,
    students: 32,
    lessons: 4,
    instructor: "SmeGear",
    image: "/businesses/groupofcompanies.webp",

    price: "₦5000",
    rating: 5,
    Views: "4375",
    UpdatedAt: "July 28, 2024",
    Category: "Business",
    overView:
      "This course is designed to help you grasp the fundamental requirements and guidance for registering a business with the Corporate Affairs Commission (CAC). Learn how to do a name search, use the CAC portal, and ensure proper registration procedures.",
    info: [
      "Step-by-step guide",
      "Thorough name search",
      "Navigate CAC portal",
      "Avoid registration errors",
      "Access to mentorship",
      "Access to daily marketing content",
      "Accredited Agent Portal",
      "Community of CAC agents",
    ],
  },
  {
    id: 5,
    title: "Business Registration",
    description: "Comprehensive Courses",
    icon: Pencil,
    students: 32,
    lessons: 4,
    instructor: "SmeGear",
    image: "/businesses/businesscommencement.webp",

    price: "₦5000",
    rating: 5,
    Views: "4375",
    UpdatedAt: "July 28, 2024",
    Category: "Business",
    overView:
      "This course is designed to help you grasp the fundamental requirements and guidance for registering a business with the Corporate Affairs Commission (CAC). Learn how to do a name search, use the CAC portal, and ensure proper registration procedures.",
    info: [
      "Step-by-step guide",
      "Thorough name search",
      "Navigate CAC portal",
      "Avoid registration errors",
      "Access to mentorship",
      "Access to daily marketing content",
      "Accredited Agent Portal",
      "Community of CAC agents",
    ],
  },
  {
    id: 6,
    title: "Business Name",
    description: "Comprehensive Courses",
    icon: Landmark,
    students: 32,
    lessons: 4,
    instructor: "SmeGear",
    image: "/businesses/businessnameregistrationcourse.webp",
    price: "₦5000",
    rating: 5,
    Views: "4375",
    UpdatedAt: "July 28, 2024",
    Category: "Business",
    overView:
      "This course is designed to help you grasp the fundamental requirements and guidance for registering a business with the Corporate Affairs Commission (CAC). Learn how to do a name search, use the CAC portal, and ensure proper registration procedures.",
    info: [
      "Step-by-step guide",
      "Thorough name search",
      "Navigate CAC portal",
      "Avoid registration errors",
      "Access to mentorship",
      "Access to daily marketing content",
      "Accredited Agent Portal",
      "Community of CAC agents",
    ],
  },
];
